remote_theme: daattali/beautiful-jekyll@6.0.1
title: Rat's Viewpoints
description: I share my views about life


navbar-links:
  - name: "Homepage"
    link: "/"
    icon: "fa fa-home"

  - name: "Posts"
    link: "/posts"
    icon: "fa fa-book"

  - name: "Projects"
    link: "/projects"
    icon: "fa fa-briefcase"